### ISSUE TITLE
Error 404, Unhandled Exception message then close.

### ISSUE THREAD

**Issue by BigChungusTM** [nerdunit/androidsideloader#33]
[crashlog.txt](https://github.com/nerdunit/androidsideloader/files/6329919/crashlog.txt)

**Comment by nerdunit** [comment]
Redownload the sideloader to a new folder or post the full logs, not just crashlog

**Comment by GasikPasik** [comment]
I have the same problem.... What should I do so that you can help me?
I add data that I considered necessary...
![Telegram_RCnDGoGrpv](https://user-images.githubusercontent.com/83033489/115770632-9cccaf00-a3b5-11eb-8d29-794840d28998.png)
[crashlog.txt](https://github.com/nerdunit/androidsideloader/files/6360622/crashlog.txt)
[debuglog.txt](https://github.com/nerdunit/androidsideloader/files/6360623/debuglog.txt)

**Comment by nerdunit** [comment]
You are missing the config, place the exe in the same folder with the rclone and adb folders, reopen if it still doesnt work

**Comment by liwenjing93** [comment]
> You are missing the config, place the exe in the same folder with the rclone and adb folders, reopen if it still doesnt work

hello, I got the same problem with him. I don't really understand which or where is the rclone and adb folders. Sorry for that, but I don't find an instruction in your github page so it's confusing for me what to do is the right thing?

I hope you can help. Thank you!

**Comment by And317956** [comment]
hola puede ser q no funcione el programa
