### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by Harveyb98** [nerdunit/androidsideloader#5]
Every time I go to install windows detects a trojan.. Don't want to install a trojan on my PC lol

**Comment by GamerBoi153** [comment]
It's not a trojan, it's open-source even. Also, I don't think it's appropriate to make this an issue. You know how much Windows Defender sucks and that antiviruses aren't perfect. (false positive, look it up) The only reason my anti virus was whining was that it wasn't signed. (which is usually something that has nothing to do with it being a virus and usually something anti-viruses hate)
Also welcome to GitHub since your account was just made today and this is the only thing you have done.

**Comment by Harveyb98** [comment]
I think it is appropriate to make it an issue so people can get an
explanation before installing something to their PC which comes up as a
trojan. No need to be all touchy about it.

**Comment by nerdunit** [comment]
It's not appropriate to make this an issue since it's not my fault it gets detected as a virus.
You can report the false positive to microsoft if you really wanted to

**Comment by GamerBoi153** [comment]
Thank you for explaining that to him.
